version: 2
updates:
  - package-ecosystem: uv
    directory: /apps/api
    schedule:
      interval: weekly
    groups:
      production-dependencies:
        dependency-type: production
      development-dependencies:
        dependency-type: development

  # GitHub uses the "npm" ecosystem identifier for npm, pnpm, and Yarn projects.
  - package-ecosystem: npm
    directory: /apps/web
    schedule:
      interval: weekly
    groups:
      production-dependencies:
        dependency-type: production
      development-dependencies:
        dependency-type: development

  - package-ecosystem: docker
    directory: /apps/api
    schedule:
      interval: weekly
    groups:
      docker-images:
        patterns:
          - "*"

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: monthly
