# Generated by Django 5.2.17 on 2026-09-06 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0019_remove_termalias_uq_term_alias_key_termalias_origin_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matchcandidate',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('grouped', 'Grouped without merging'), ('rejected', 'Rejected'), ('abstained', 'Abstained')], default='pending', max_length=16),
        ),
        migrations.AlterField(
            model_name='matchdecision',
            name='outcome',
            field=models.CharField(choices=[('bind', 'Bind'), ('group', 'Group without merging'), ('reject', 'Reject'), ('abstain', 'Abstain')], max_length=16),
        ),
    ]
