# Generated by Django 5.2.17 on 2026-09-07 17:19

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0020_add_identity_group_outcome'),
    ]

    operations = [
        migrations.CreateModel(
            name='AiringBoard',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('season_key', models.CharField(blank=True, max_length=16)),
                ('status', models.CharField(choices=[('active', 'Active'), ('archived', 'Archived')], default='active', max_length=16)),
                ('item_count', models.PositiveIntegerField(default=0)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('effective_from', models.DateTimeField(blank=True, null=True)),
                ('effective_until', models.DateTimeField(blank=True, null=True)),
                ('observation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='airing_boards', to='index.observation')),
            ],
            options={
                'db_table': 'airing_board',
                'indexes': [models.Index(fields=['status', '-effective_from'], name='idx_airing_board_status'), models.Index(fields=['season_key', 'status'], name='idx_airing_board_season')],
                'constraints': [
                    models.CheckConstraint(condition=models.Q(('status__in', ('active', 'archived'))), name='ck_airing_board_status'),
                    models.UniqueConstraint(condition=models.Q(('status', 'active')), fields=['status'], name='uq_airing_board_single_active'),
                ],
            },
        ),
    ]
