# Generated by Django 5.2.17 on 2026-09-08 05:40

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0021_airingboard'),
    ]

    operations = [
        migrations.CreateModel(
            name='AiringBoardEntry',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('episode_number', models.PositiveIntegerField(blank=True, null=True)),
                ('weekday', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('starts_at', models.DateTimeField(blank=True, null=True)),
                ('timezone', models.CharField(blank=True, max_length=64)),
                ('region', models.CharField(blank=True, max_length=16)),
                ('duration_minutes', models.PositiveIntegerField(blank=True, null=True)),
                ('precision', models.CharField(choices=[('minute', 'Minute'), ('day', 'Day'), ('weekday', 'Weekday'), ('unknown', 'Unknown')], default='unknown', max_length=16)),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('tentative', 'Tentative'), ('finished', 'Finished')], default='tentative', max_length=16)),
                ('decision', models.CharField(choices=[('consensus', 'Consensus'), ('source_priority', 'Source priority'), ('manual', 'Manual'), ('ai', 'AI')], default='source_priority', max_length=32)),
                ('confidence', models.DecimalField(decimal_places=4, default=Decimal('1.0000'), max_digits=5)),
                ('source_refs', models.JSONField(blank=True, default=list)),
                ('board', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='index.airingboard')),
                ('episode_entity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='airing_board_entries', to='index.entity')),
                ('work', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='airing_board_entries', to='index.work')),
            ],
            options={
                'db_table': 'airing_board_entry',
                'indexes': [models.Index(fields=['board', 'weekday'], name='idx_board_weekday'), models.Index(fields=['board', 'starts_at'], name='idx_board_starts_at')],
                'constraints': [models.CheckConstraint(condition=models.Q(('weekday__isnull', True), ('weekday__range', (1, 7)), _connector='OR'), name='ck_airing_board_weekday'), models.UniqueConstraint(fields=('board', 'work', 'episode_number', 'starts_at', 'timezone'), name='uq_airing_board_slot', nulls_distinct=False)],
            },
        ),
    ]
