# Generated by Django 5.2.17 on 2026-09-29 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0024_animeprofile_broadcast_run'),
    ]

    operations = [
        migrations.AddField(
            model_name='work',
            name='popularity',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='work',
            name='popularity_refreshed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name='work',
            index=models.Index(fields=['-popularity'], name='idx_work_popularity'),
        ),
    ]
