# Generated by Django 5.2.17 on 2026-09-30 08:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0025_work_popularity'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DataMigrationCheckpoint',
        ),
        migrations.DeleteModel(
            name='DataMigrationRun',
        ),
    ]
