# Generated by Django 5.2.17 on 2026-09-29 07:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0020_remove_usersubject_uq_user_subject_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SocialIdentity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(choices=[('github', 'GitHub')], max_length=32)),
                ('subject', models.CharField(max_length=191)),
                ('handle', models.CharField(blank=True, max_length=191)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('avatar_url', models.URLField(blank=True, max_length=1024)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='social_identities', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'social_identity',
                'indexes': [models.Index(fields=['user', 'provider'], name='idx_social_identity_user')],
                'constraints': [models.UniqueConstraint(fields=('provider', 'subject'), name='uq_social_identity_subject')],
            },
        ),
    ]
