# Generated by Django 5.2.17 on 2026-09-09

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ai", "0004_remove_agentrun_uq_agent_run_idempotency_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="AgentMessage",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("sequence", models.PositiveIntegerField()),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("system", "System"),
                            ("user", "User"),
                            ("assistant", "Assistant"),
                            ("tool", "Tool"),
                        ],
                        max_length=16,
                    ),
                ),
                ("name", models.CharField(blank=True, max_length=128)),
                ("tool_call_id", models.CharField(blank=True, max_length=128)),
                ("content", models.TextField(blank=True)),
                ("tool_calls", models.JSONField(blank=True, default=list)),
                ("content_hash", models.CharField(blank=True, max_length=64)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "run",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="messages",
                        to="ai.agentrun",
                    ),
                ),
            ],
            options={
                "db_table": "agent_message",
                "ordering": ["run", "sequence"],
            },
        ),
        migrations.AddConstraint(
            model_name="agentmessage",
            constraint=models.UniqueConstraint(
                fields=("run", "sequence"),
                name="uq_agent_message_run_sequence",
            ),
        ),
        migrations.AddIndex(
            model_name="agentmessage",
            index=models.Index(
                fields=["run", "sequence"],
                name="idx_agent_message_run_seq",
            ),
        ),
    ]
