# Generated by Django 5.2.17 on 2026-09-07 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sync', '0015_syncworkitem_ai_enriched_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='syncjob',
            name='job_type',
            field=models.CharField(choices=[('subject_bangumi', 'Subject by Bangumi'), ('subject_resync', 'Subject resync'), ('vndb_import', 'VNDB import'), ('anilist_import', 'AniList import'), ('calendar', 'Calendar'), ('airing_daily', 'Airing daily refresh'), ('incremental', 'Incremental')], max_length=64),
        ),
    ]
