/**
 * Files served straight from `public/`, referenced by absolute URL.
 *
 * The icon set is generated by `pnpm icons` from `public/assets/brand/mark.png`;
 * nothing else should hardcode these paths.
 */
export const publicAssetPaths = {
  /** App tile: the browser tab, the installed app and the in-app logo. */
  appIcon: '/icon-512.png',
  /** Maintainer portrait shown on the documentation pages. */
  owner: '/assets/owner.png',
} as const;
